name: build and test simple
# on: [push]
on:
  push:
    # branches:
    #   - master
    paths:
      - "**.rs"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-n-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
